name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "deploy/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "deploy/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - run: git tag ${{ steps.version.outputs.version }}
      - run: git push origin ${{ steps.version.outputs.version }}    

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push CleanAspire.Standalone image
      #   run: |
      #       docker build -t ${{ secrets.DOCKER_USERNAME }}/cleanaspire-standalone:${{ steps.version.outputs.version }} -f src/CleanAspire.ClientApp/Dockerfile .
      #       docker push ${{ secrets.DOCKER_USERNAME }}/cleanaspire-standalone:${{ steps.version.outputs.version }}    
      # - name: Build and push CleanAspire.WebApp image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/cleanaspire-webapp:${{ steps.version.outputs.version }} -f src/CleanAspire.WebApp/Dockerfile .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/cleanaspire-webapp:${{ steps.version.outputs.version }}

      # - name: Build and push CleanAspire.Api image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/cleanaspire-api:${{ steps.version.outputs.version }} -f src/CleanAspire.Api/Dockerfile .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/cleanaspire-api:${{ steps.version.outputs.version }}

      - name: Update docker-compose file with new version
        run: |
          sed -i "s|blazordevlab/cleanaspire-api:[0-9.]*|blazordevlab/cleanaspire-api:${{ steps.version.outputs.version }}|g" deploy/docker-compose.yml
          sed -i "s|blazordevlab/cleanaspire-webapp:[0-9.]*|blazordevlab/cleanaspire-webapp:${{ steps.version.outputs.version }}|g" deploy/docker-compose.yml
          sed -i "s|blazordevlab/cleanaspire-standalone:[0-9.]*|blazordevlab/cleanaspire-standalone:${{ steps.version.outputs.version }}|g" deploy/docker-compose.yml

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create Pull Request to update docker-compose version
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          commit-message: "Update docker-compose versions to ${{ steps.version.outputs.version }}"
          branch: update-docker-compose-${{ steps.version.outputs.version }}
          title: "Update docker-compose versions to ${{ steps.version.outputs.version }}"
          body: |
            This PR updates the image versions in deploy/docker-compose.yml to ${{ steps.version.outputs.version }}.
